// Von Hand kuratierte Angaben. Jeder Eintrag nennt seine Quelle (Artikeltitel im Wiki). "d" = Dossier, "e" = Ergänzungsartikel (Entwurf/Kanon des Autors).
const g = (term, def, src, k = 'd', alias = []) => ({ term, def, src, k, alias });

export const CURATED = {
  persons: [
    { name: 'Henrike Adamczyk', role: 'erste Geschäftsführerin der Saumland AG; ließ den Satz „Wer das Land bewohnt, besitzt es, wer es besitzt, schuldet ihm“ in den Gründungsvertrag schreiben', org: 'Saumland AG', src: 'Saumland AG', k: 'd' },
    { name: 'Dmitri Kessel-Adeyemi', role: 'Gründer von Ostpfad Kolonisation; nannte seine Route den „östlichen Pfad“', org: 'Ostpfad Kolonisation', src: 'Ostpfad Kolonisation', k: 'd' },
    { name: 'Keala Mahoe-Brandt', role: 'Gründerin der Ola AG, ehemalige Meeresbiologin', org: 'Ola AG', src: 'Ola AG', k: 'd' },
    { name: 'Rafael Sousa-Quispe', role: 'Gründer von Chama Motores', org: 'Chama Motores AG', src: 'Chama Motores AG', k: 'd' },
    { name: 'Selin Aydoğan-Vance', role: 'Gründerin von Dalga, verehrt als „Mutter des Wellenantriebs“', org: 'Dalga', src: 'Dalga', k: 'd' },
    { name: 'Ilse Varga-Mbeki', role: 'Gründerin der Solaren Antimaterie-Werke (Dr.)', org: 'Solare Antimaterie-Werke (SAW)', src: 'Solare Antimaterie-Werke (SAW)', k: 'd' },
    { name: 'Tanabe-Okonkwo (Familie)', role: 'Gründerfamilie von Seimitsu, stellt bis heute den Aufsichtsratsvorsitz', org: 'Seimitsu', src: 'Seimitsu', k: 'd' },
    { name: 'Tomasz Wieczorek-Ndiaye', role: 'junger Ingenieur bei Grundstein, schlug vor, daraus Wohnmodule zu pressen', org: 'Grundstein-Gruppe', src: 'Grundstein-Gruppe', k: 'd' },
    { name: 'Amani Okonkwo-Reyes', role: 'Direktor von Nguvu Moto, für seine Verhandlungen gefürchtet', org: 'Nguvu Moto', src: 'Nguvu Moto', k: 'd' },
    { name: 'Leilani Akana-Rivière', role: 'Gründerin der Hōkū AG', org: 'Hōkū AG', src: 'Hōkū AG', k: 'd' },
    { name: 'Matthias Lindqvist-Amadi', role: 'Theaterdirektor und Gründer der Sternfahrt-Gesellschaft', org: 'Sternfahrt-Gesellschaft', src: 'Sternfahrt-Gesellschaft', k: 'd' },
    { name: 'Karl-Heinz Obuya-Stern', role: 'Gründer der Weitgang-Linien', org: 'Weitgang-Linien', src: 'Weitgang-Linien', k: 'd' },
    { name: 'Ilse Nakamura-Reyes', role: 'Leiterin der Meridian-Expedition (Planetenbiologie, Dr.)', org: 'Expedition der Meridian', src: 'Die Expedition der Meridian', k: 'd' },
    { name: 'Orlando Peixoto', role: 'Kommandant der FS Meridian', org: 'Expedition der Meridian', src: 'Die Expedition der Meridian', k: 'd' },
    { name: 'Faizan Qureshi', role: 'Biosicherheitsleiter der Meridian-Expedition (Dr.); legte als Erster im Lager den Helm ab', org: 'Expedition der Meridian', src: 'Die Expedition der Meridian', k: 'd' },
    { name: 'Katarzyna Lindahl', role: 'Ökologin der Meridian-Expedition (Dr.)', org: 'Expedition der Meridian', src: 'Die Expedition der Meridian', k: 'd' },
  ],

  // Beteiligungen und Töchter, jeweils mit Angabe der Quelle (Firmenporträts bzw. Monopole und Marktmacht)
  ownership: [
    { owner: 'Saumland AG', sub: 'Saumbank', w: 'Tochter', src: 'Saumland AG' },
    { owner: 'Saumland AG', sub: 'Saumbau', w: 'Tochter', src: 'Saumland AG' },
    { owner: 'Saumland AG', sub: 'Weitgang-Linien', w: 'Mehrheit (58 % der Linien)', src: 'Saumland AG' },
    { owner: 'Saumland AG', sub: 'Ola AG', w: '35 %', src: 'Saumland AG' },
    { owner: 'Kornmark-Gruppe', sub: 'Kornsaum Agrar', w: 'Tochter', src: 'Kornmark-Gruppe' },
    { owner: 'Kornmark-Gruppe', sub: 'Kornstraße AG', w: 'Tochter', src: 'Kornmark-Gruppe' },
    { owner: 'Kornmark-Gruppe', sub: 'Kornmark Baustoffe', w: 'Tochter', src: 'Kornmark-Gruppe' },
    { owner: 'Ostpfad Kolonisation', sub: 'Námumenn', w: '51 %', src: 'Ostpfad Kolonisation' },
    { owner: 'Ostpfad Kolonisation', sub: 'Werftbund', w: '50 %', src: 'Werftbund' },
    { owner: 'Grundstein-Gruppe', sub: 'Werftbund', w: '50 %', src: 'Werftbund' },
    { owner: 'Grundstein-Gruppe', sub: 'Grundstein Schwerwerke', w: 'Tochter', src: 'Grundstein-Gruppe' },
    { owner: 'Grundstein-Gruppe', sub: 'Grundstein Modulbau', w: 'Tochter', src: 'Grundstein-Gruppe' },
    { owner: 'Randmark-Gesellschaft', sub: 'Porvölgy Érc', w: 'Tochter', src: 'Randmark-Gesellschaft' },
    { owner: 'Randmark-Gesellschaft', sub: 'Randmark Bau', w: 'Tochter', src: 'Randmark-Gesellschaft' },
    { owner: 'Ceres-Kontor', sub: 'Cevher AG', w: '30 %', src: 'Ceres-Kontor' },
    { owner: 'Ceres-Kontor', sub: 'Yaku', w: '20 %', src: 'Ceres-Kontor' },
    { owner: 'Ceres-Kontor', sub: 'Czysto AG', w: '20 %', src: 'Ceres-Kontor' },
    { owner: 'Ceres-Kontor', sub: 'Ghawwas', w: '15 %', src: 'Ceres-Kontor' },
    { owner: 'Ceres-Kontor', sub: 'Asfaleia', w: '10 %', src: 'Ceres-Kontor' },
    { owner: 'Bund', sub: 'Lutang AG', w: '40 %', src: 'Monopole und Marktmacht' },
    { owner: 'Bund', sub: 'Kiran AG', w: '40 % (Sperrminorität)', src: 'Monopole und Marktmacht' },
    { owner: 'Bund', sub: 'Ghawwas', w: '25 %', src: 'Monopole und Marktmacht' },
    { owner: 'Bund', sub: 'Solare Antimaterie-Werke (SAW)', w: '100 %', src: 'Monopole und Marktmacht' },
    { owner: 'Bund', sub: 'Solare Raumwerft (SRW)', w: '100 %', src: 'Monopole und Marktmacht' },
    { owner: 'Bund', sub: 'Ringwerk', w: '100 %', src: 'Monopole und Marktmacht' },
    { owner: 'Bund', sub: 'Terra-Fährverbund', w: '100 % (Anstalt öffentlichen Rechts)', src: 'Monopole und Marktmacht' },
    { owner: 'Bund', sub: 'Solare Post', w: '100 % (Postregal)', src: 'Monopole und Marktmacht' },
  ],

  // Astronomische Standardwerte, soweit die Dossiers keinen Bahnradius nennen (große Halbachse in AE)
  bodies: [
    { name: 'Merkur', au: 0.387, std: false }, { name: 'Venus', au: 0.723, std: false }, { name: 'Erde', au: 1.0, std: false }, { name: 'Mars', au: 1.524, std: false },
    { name: 'Ceres', au: 2.77, std: true }, { name: 'Jupiter', au: 5.203, std: true }, { name: 'Saturn', au: 9.537, std: true },
    { name: 'Uranus', au: 19.19, std: true }, { name: 'Neptun', au: 30.07, std: true }, { name: 'Pluto', au: 39.48, std: true },
  ],

  constants: { c_kms: 299792.458, au_km: 149597870.7, ly_km: 9.4607304725808e12, g: 9.80665, year_d: 365.25, zoneR0_km: 2e6, credit_eur: 0.5 },

  glossary: [
    // Recht und Staat
    g('Solarrepublik', 'Der Staat der Menschheit, seit dem Vertrag von Shackleton (2074). Die Erdstaaten sind Regionen, die Kolonien Provinzen oder Territorien; Regierungssitz ist Luna.', 'Die Solarrepublik'),
    g('Region', 'Gebiet der Solarrepublik auf der Erde; die Erde gliedert sich in zwölf Regionen.', 'Die Solarrepublik'),
    g('Provinz', 'Gebiet der Solarrepublik im Sonnensystem; es gibt acht Provinzen.', 'Die Solarrepublik'),
    g('Territorium', 'Gebiet mit eigener Regierung und eigener Verfassung; die sechs Nachbarsysteme sind Territorien.', 'Die Solarrepublik'),
    g('Solarparlament', 'Gesetzgebendes Organ mit 630 Sitzen (personalisierte Verhältniswahl, 4 Jahre); wählt den Kanzler.', 'Die Solarrepublik'),
    g('Rat der Systeme', 'Kammer der Gebiete mit 114 Stimmen (12 Erdregionen je 5, 8 Provinzen je 3, 6 Territorien je 5); stimmt Gesetzen zu, die Gebiete berühren.', 'Die Solarrepublik'),
    g('Solarversammlung', 'Parlament plus ebenso viele Delegierte der Gebiete; wählt die Solarpräsident(in) für 5 Jahre.', 'Die Solarrepublik'),
    g('Konstruktives Misstrauensvotum', 'Der Kanzler kann nur abgewählt werden, indem das Parlament zugleich einen Nachfolger wählt.', 'Die Solarrepublik'),
    g('Volksinitiative', 'Zulassung eines Anliegens ab 1 % der Wahlberechtigten (≈ 73 Mio.); das Parlament berät.', 'Direkte Demokratie'),
    g('Volksbegehren', 'Gesetzentwurf per 5 % der Wahlberechtigten in 6 Monaten; geht zum Volksentscheid, wenn das Parlament ablehnt.', 'Direkte Demokratie'),
    g('Abstimmungstag', 'Zweimal im Jahr (Frühjahr, Herbst) stimmen alle Gebiete am selben Tag ab; Kurierstimmen reisen mit den Windhund-Linern.', 'Direkte Demokratie'),
    g('Solarstimme', 'Abstimmungs-App der Solarrepublik; läuft pro System, die Stimmen reisen als Kurierstimmen per Schiff.', 'Solarstimme', 'e'),
    g('Charta', 'Die Solare Charta, grundlegendes Gesetz; ihr Kernbestand (Würde, Leben, Freiheit, Atemluft und Grundversorgung, Rückkehr, faires Verfahren) kann auch ein Konzern nicht abschaffen.', 'Solare Charta (SolCh)'),
    g('Charta-Abkommen', 'Abkommen zwischen Sol und einer Charta-Kolonie; gilt im jeweiligen Siedlungssystem.', '2. Rechtsquellen und ihr Rang'),
    g('Kernrecht', 'Rechtskreis: Die Sol-Regierung auf Luna regiert, es gilt volles Sol-Recht (Sol-System und Orte, die unmittelbar Sol unterstehen).', '3. Rechtskreise: Wo gilt welches Recht?'),
    g('Stationsrecht', 'Rechtskreis: Auf Raumstationen, die Luna gehören, gilt Luna-Recht; außerhalb der Station gilt das Recht des jeweiligen Systems.', '3. Rechtskreise: Wo gilt welches Recht?'),
    g('Chartarecht', 'Rechtskreis: Die lokale Regierung des Systems regiert; lokales Recht innerhalb der Charta-Abkommen, Sol-Recht nach Maßgabe des Abkommens.', '3. Rechtskreise: Wo gilt welches Recht?'),
    g('Konzernrecht', 'Rechtskreis: In Systemen ohne Luna-Station darf die gründende Firma nahezu jeden Lebensbereich selbst regeln; der Kernbestand der Charta gilt fort, wird aber nur eingeschränkt durchgesetzt.', '3. Rechtskreise: Wo gilt welches Recht?'),
    g('Luna-Station', 'Raumstation, die Sol gehört und der Verwaltung von Luna untersteht; ab 1 Mio. Einwohnern errichtet die Solarrepublik per Regierungsbeschluss eine (Siedlungsschutzgesetz 2223).', 'Stationsgesetz (StatG)'),
    g('Hoheitsstation', 'Station des Bundes in einem Territorium oder einer Konzessionskolonie: Torkontrolle des Bundes, Raumwache-Kampfgruppe; im Wolf-1061-System seit 2231.', 'Das Militär: Solare Raumwache'),
    g('Konzessionskolonie', 'Kolonie, die eine Firma im Auftrag des Bundes betreibt; Beispiel Wolf 1061 (Randmark-Gesellschaft, Hoheitsstation seit 2231).', 'Konzerne, Konzessionen und Konzernkolonien'),
    g('Konzernkolonie', 'Kolonie der gründenden Firma ohne Luna-Station; die Raumwache stationiert dort nicht (Gliese 667 C, TRAPPIST-1, LHS 1140).', 'Konzerne, Konzessionen und Konzernkolonien'),
    g('Regelsatz', 'Der von Sol jährlich festgesetzte monatliche Grundbedarf eines Erwachsenen; Maßstab für Schwellen und Unterhalt im Recht.', 'Vorwort und Lesehinweise'),
    g('Tagessatz', 'Geldstrafen werden in Tagessätzen verhängt, die sich nach dem Einkommen des Täters richten.', 'Vorwort und Lesehinweise'),
    g('Gemeinwerk', 'Gemeinnützige Arbeit als Strafart.', '8. Strafen und Vollzug im Überblick'),
    g('Kommandoverbot', 'Nebenfolge: Entzug der Erlaubnis zum Führen von Raumfahrzeugen.', '8. Strafen und Vollzug im Überblick'),
    g('Solare Standardzeit', 'Zeitbezug für Fristen zwischen Systemen; Habitate dürfen für den Innenverkehr ortsübliche Zeit festlegen.', 'SolBGB: Buch 1: Allgemeiner Teil'),
    g('Kartellamt', 'Das Solare Kartellamt (Ministerium für Wirtschaft und Ressourcen) prüft Fusionen und Absprachen, aber nur dort, wo Solarrecht gilt.', 'Monopole und Marktmacht'),
    g('Solarbank', 'Unabhängige Zentralbank (Direktorium 8 Jahre), verwaltet die Währung Credit; Sitz im Terra-Ring.', 'Die Solarrepublik'),
    g('Solarfonds', 'Finanzausgleich zwischen den Gebieten beim Finanzministerium.', 'Die Solarrepublik'),
    g('Credit', 'Währung der Solarrepublik (Cr). Die Wirtschaft erzeugt ≈ 760 Bio. Cr im Jahr (≈ 80.000 Cr je Kopf); eine Passage kostet 3.000 bis 15.000 Cr.', '4. Geld und Konzerne'),
    g('Solbürgerschaft', 'Bürgerschaft in der Solarrepublik; Grundlage für Bewerbungen um Planeten- oder Koloniebürgerschaften.', 'Solbürgerschaft', 'e'),
    // Planetenschutz und Leben
    g('Schwarzfilm', 'Radiotrophus proximae: Einzeller (1–3 µm), der Strahlung in Energie umsetzt; 2186 im Saum von Proxima b entdeckt, für Menschen nicht pathogen.', 'Der Schwarzfilm'),
    g('Saumschwarz', 'Melaninähnlicher Pigmentkomplex des Schwarzfilms, der Gamma-, Röntgen- und Teilchenstrahlung in chemische Energie wandelt.', 'Der Schwarzfilm'),
    g('Filmhusten', 'Harmlose, kurze Atemwegsreizung durch den Sporenstaub des Schwarzfilms.', 'Der Schwarzfilm'),
    g('Dekontamination', 'Seit 2203 Pflicht an allen Randhäfen: Scan (Abstrich und Probe ≈ 6 Stunden) und Sprühwäsche jedes ankommenden Schiffs.', 'Dekontamination'),
    g('Dunkeldock', 'Dock für befallene Schiffe (Stufe 2, ≈ 0,4 % der Ankünfte): 3 Tage Dunkelheit, dann 4 Stunden Heißdampf von mindestens 140 °C; Freigabe durch das BPS nach ≈ 5 Tagen.', 'Dekontamination'),
    g('BPS', 'Bundesamt für Planetenschutz (Sitz Luna, ≈ 2.300 Beschäftigte) im Ministerium für Wissenschaft, Bildung und Umwelt; Einstufung der Welten, Gutachten, Dunkeldocks.', 'Planetenschutz: Recht und Behörden'),
    g('Schutzkategorie', 'Einstufung von Welten durch das BPS: A Vollschutz (Europa, Enceladus), B Schutz mit Gutachten, C Siedlung mit Auflagen (Proxima b), D Standard.', 'Planetenschutz: Recht und Behörden'),
    g('Bestandsschutz', 'In Kategorie B behalten Inhaber, die ihre Rechte vor der Einstufung erwarben, ihre Rechte.', 'Die Anwartschaften des Ceres-Kontors'),
    g('Quarantäne', 'Mindestens zwei Wochen für Ankömmlinge von neu besuchten Welten, etwa TOI-700 d.', 'Quarantäne und Gesundheit', 'e'),
    // Raum, Zonen, Verkehr
    g('Sperrzone', 'Raumbereich um einen Stern oder Körper, in dem das Zünden des Metrischen Wellenantriebs verboten ist.', 'SperrZG: Abschnitt 1: Allgemeine Vorschriften'),
    g('Zonenradius', 'Planetare Sperrzone: R = R₀ · (Mp / M⊕)^(1/3) mit R₀ = 2 Mio. km; die Sperrzone der Sonne reicht ≈ 0,93 AE.', 'sperrzonen-sonnensystem-2234-grundlagen-der-sperrzonen'),
    g('Zonenrand', 'Grenzfläche einer Sperrzone.', 'SperrZG: Abschnitt 1: Allgemeine Vorschriften'),
    g('Schattenzone', 'Raumbereich innerhalb einer stellaren Zone, der nicht selbst als Zündort zugelassen ist (Merkur, Venus).', 'SperrZG: Abschnitt 1: Allgemeine Vorschriften'),
    g('Sperrschatten', 'Raumbereich in Zündrichtung hinter dem Zündpunkt, der den Auswirkungen der Zündung ausgesetzt sein kann.', 'SperrZG: Abschnitt 1: Allgemeine Vorschriften'),
    g('Zündpunkt', 'Ort, an dem ein Fahrzeug nach den Vorschriften des Sperrzonengesetzes zünden darf.', 'SperrZG: Abschnitt 1: Allgemeine Vorschriften'),
    g('Korridor', 'Der durch die Zonenbehörde zugewiesene Flugweg zwischen Zonenrand und Ziel oder Start.', 'SperrZG: Abschnitt 1: Allgemeine Vorschriften'),
    g('Gateway-Sektor', 'Am Rand der stellaren Zone mitlaufender Übergabepunkt (Alpha bis Delta), in dem Fahrzeuge aus dem Innern der Zone zünden dürfen; vom Zonenamt verwaltet.', 'SperrZG: Abschnitt 1: Allgemeine Vorschriften'),
    g('Zonenamt', 'Bundesbehörde, die Gateway-Sektoren verwaltet und Zündfreigaben erteilt (Anmeldung spätestens sechs Stunden vor der Zündung).', 'SperrZG: Abschnitt 2: Zündung, Korridor, Notfall'),
    g('Randhafen', 'Station auf der Zonengrenze mit vier Toren (A–D) im Tetraeder-Abstand; RH-Terra liegt bei ≈ 2 Mio. km, RH-Ares bei ≈ 0,95 Mio. km.', 'Anatomie eines Randhafens'),
    g('Torkontrolle', 'Bundesbehörde des Transportministeriums für Freigaben an den Toren; Zonenwache und Lotsenaufsicht gehören dazu.', 'Flugsicherung und Lotsenwesen'),
    g('Ankerpunkt', 'Wartepunkt vor einer Welt (z. B. 200.000 km bei Proxima b), von dem Fähren den Rest fliegen.', 'Proxima Centauri'),
    g('Äquatorring', 'Ring um die Erde in 300 km Höhe mit zwölf Speichenliften für Passagiere (Metalle aus Vesta und Psyche, Baubeginn 2158).', 'Erde, Mond und Erdorbit'),
    g('Terra-Fahrstuhl', 'Weltraumfahrstuhl der Erde (Betrieb seit 2143), Kopfstation ≈ 100.000 km; Magnetläufer bis 2.000 km/h seit 2189.', 'Zeitleiste der Besiedlung'),
    g('Ares-Fahrstuhl', 'Weltraumfahrstuhl des Mars (Betrieb seit 2221).', 'Zeitleiste der Besiedlung'),
    g('Startschleife', 'Beschleunigungsanlage für Massengut, in Betrieb seit 2207.', 'Zeitleiste der Besiedlung'),
    g('Lagrange-Habitat', 'Großstation an einem der Lagrange-Punkte des Erdsystems.', 'Erde, Mond und Erdorbit'),
    g('Terra-Ring', 'Orbitale Ringsiedlung im geostationären Orbit aus 93 Reif-3 (≈ 14 Mio. Einwohner); Sitz der Solarbank.', 'Serienhabitate'),
    g('Serienhabitat', 'Eine von zwölf Serien von Bauformen für Habitate (z. B. Reif, Walze, Röhre, Stapel, Floß, Kerbe, Halbrund, Tiefe, Schwebe).', 'Habitate und Bauweisen'),
    g('Aerostat', 'Schwebende Stadt in der Venus-Atmosphäre (52–55 km Höhe), gebaut von Lutang AG.', 'Venus'),
    g('Kuppelstadt', 'Stadt unter einer Druckkuppel; größte Gruppe ist Hellas auf dem Mars (≈ 24 Mio.).', 'Serienhabitate'),
    g('Saum', 'Das bewohnbare Dämmerungsband von Proxima b zwischen heißer Tag- und dunkler Nachtseite.', 'Proxima Centauri'),
    g('Ring (TOI-700 d)', 'Dämmerungsband der gebunden rotierenden Welt, 55–95° vom Substellarpunkt; Wälder, Seen, Randmeere; hier ist die Luft atembar.', 'Der Bericht des Teams (Hauptbericht, 24. August 2235)'),
    // Antriebe und Schiffe
    g('Metrischer Wellenantrieb', 'FTL-Antrieb (Klasse I, seit 2198), komprimiert die Raumzeit vor und expandiert sie hinter dem Schiff; 10c bis 100c.', 'Überlichtgeschwindigkeits-Antriebe (FTL)'),
    g('Resonatorring', 'Hauptbauteil des Wellenantriebs; gebaut von Dalga, Bølge und Zhenbo in Lizenz.', 'Überlichtgeschwindigkeits-Antriebe (FTL)'),
    g('Pellets', 'Katalysatorpellets mit Antiprotonen-Dosis; nur die Solaren Antimaterie-Werke stellen sie her. Ohne sie fliegt kein FTL-Schiff.', 'Monopole und Marktmacht'),
    g('MPD-Antrieb', 'Magnetoplasmadynamische Düsen (seit den 2040ern): Standardantrieb im System, 30–100 km/s; Energie aus Orbitalkraftwerken.', 'Kurzstrecken- & Systeminterne Antriebe'),
    g('Fusionspuls', 'Antimaterie-katalysierter Fusionspuls (seit 2068), 100–1.000 km/s, höchstens 0,1–0,15c; Arbeitstier für Fracht und Bergbau.', 'Relativistische Sublichtantriebe'),
    g('Magneto-Bussard', 'Kollektor-Antrieb (seit 2115), 0,2–0,3c; Hōkū AG baut die Trichterspulen als Monopolist.', 'Relativistische Sublichtantriebe'),
    g('Pionen-Antrieb', 'Antimaterie-Pionen-Antrieb (seit 2154): typisch 0,03–0,08c, Konstruktionsmaximum 0,5c, Rekord 0,8c im Vorbeiflug; nur der Bund besitzt Pionenschiffe.', 'Relativistische Sublichtantriebe'),
    g('Quantentunnel', 'FTL Klasse X: Sprung in Null Zeit; experimentell, geheim, unbemannt; Prototypen seit 2228 (Q-Reihe).', 'Makroskopischer Quantentunnel (FTL Klasse X)'),
    g('Fehlkollaps', 'Beim Quantentunnel kollabiert der Zustand an falschem Ort oder gar nicht; auf 101 ly lag die Rate 2234 bei ≈ 57 %.', 'Das Sofortprogramm: Sonden per Quantentunnel'),
    g('Windhund', 'Schneller Liner (80–100c), Personen- und Postverkehr.', '2. Wie man reist'),
    g('Landnahme', 'Siedlerliner (40c).', '2. Wie man reist'),
    g('Karawane', 'Frachtliner (20c).', '2. Wie man reist'),
    g('Bollwerk', 'Trägerschiff der Raumwache (60 Stück, je 12 Nadeln); kann kein FTL, bleibt in seinem System.', 'Das Militär: Solare Raumwache'),
    g('Nadel', 'Kleine Kampfeinheit der Raumwache (bis 10 g), von Bollwerken getragen; 720 Nadeln insgesamt.', 'Das Militär: Solare Raumwache'),
    g('Fernwache', 'Patrouillenarm der Raumwache: 25 Schiffe, besuchen Randwelten alle 6–8 Jahre; Papiere, Rettung, Planetenschutz-Kontrolle.', 'Das Militär: Solare Raumwache'),
    g('Q-Reihe', 'Quantentunnel-Prototypen des Amts für Sonderprojekte.', 'Amt für Sonderprojekte', 'e'),
    // Wirtschaft
    g('Anwartschaft', 'Recht, im künftigen Zuteilungsverfahren bevorzugt berücksichtigt zu werden (§ 8 TOI-RahmG); kein Besitz an Land.', 'Die Anwartschaften des Ceres-Kontors'),
    g('Fernziel-Fonds', 'Vom Ceres-Kontor verwaltetes Sondervermögen mit Anwartschaften auf sieben Welten jenseits von 75 ly.', 'Die Anwartschaften des Ceres-Kontors'),
    g('Moratorium', 'Bis 2240: keine Landung auf TOI-700 d ohne Genehmigung der Bundesregierung.', 'Querverweise'),
    g('Zuteilungsverfahren', 'Verfahren, in dem Land auf TOI-700 d verteilt werden soll; noch nicht eröffnet.', 'Die Anwartschaften des Ceres-Kontors'),
    g('Claim', 'Gehandelter Anspruch auf eine Welt oder Fläche; Claims werden an der Ceres-Börse gehandelt.', 'Ceres-Kontor'),
    g('Claim-Index', 'Preisindex der Claims; bricht 2221 nach der Landnahme-Blase um 71 % ein.', 'Ceres-Kontor'),
    g('Ceres-Index', 'Index der Frachtbörse des Ceres-Kontors (≈ 70 % der Buchungen).', 'Ceres-Kontor'),
    g('Ceres-Freihafen', 'Erster FTL-Freihafen außerhalb der Sonnenzone (seit 2208).', 'Zeitleiste der Besiedlung'),
    g('Landrecht', 'Recht an Land in einer Kolonie; Saumland vergibt seine als Erbpacht auf 99 Jahre.', 'Saumland AG'),
    g('Erbpacht', 'Langfristige Landnutzung gegen Entgelt; bei Saumland auf 99 Jahre.', 'Saumland AG'),
    g('Kartograph', 'Kartographisches Amt im Transportministerium; Erstbewertung neuer Welten.', 'Die Solarrepublik'),
    g('Koloniewert', 'Bewertung jeder Welt im Sol-Sektor; Stufen K1 (Terraform-Ziele), K2 (Kuppelwelten), K3 (Sonderwelten), K4 (Stützpunkte).', 'Sternkarte und Koloniewelten'),
    g('Setzung', 'Zahl oder Festlegung der Dossiers, die sich aus Flottenzahlen, Bevölkerung und Tarifen ergibt und im Setting verbindlich ist.', 'Firmenverzeichnis und Marktmacht'),
    g('Zollunion von Rangimarie', 'Abkommen von Rangimarie (2211): Zollunion der Nachbarsysteme.', 'Zeitleiste der Besiedlung'),
    g('Kuriersynchronisation', 'Abgleich von Netzdaten zwischen Systemen, der nur per Schiff geschieht.', 'Kommunikation, Netz und KI', 'e'),
    g('Beschäftigungsbindung', 'Grauzone der Ansiedlungsverträge: Bindung an einen Arbeitgeber bis zu 12 Jahren, obwohl Schuldknechtschaft verboten ist.', 'Ansiedlungsverträge und Beschäftigungsbindung', 'e'),
    // Ergänzungen des Autors
    g('Koloniekrieg', 'Konflikt 2119–2123 zwischen den Erdregierungen und einem Gürtelbündnis; Wolframstäbe zerstörten Anlagen auf Ganymed und Mars.', 'Koloniekrieg 2119–2123', 'e'),
    g('Wolfram-Verbot', 'Verbot der kinetischen Bombardierung bewohnter Körper, Teil des Friedens von Occator (2123).', 'Frieden von Occator', 'e'),
    g('Himal-Plan', 'Umweltprogramm („Erdschutzakte“) von 2091 nach Mingma Tamang: Kreislaufwirtschaft, Industrie ins All, Renaturierung.', 'Himal-Plan', 'e'),
    g('Sonderabteilung', 'Geheimpolizei der Solarrepublik (seit 2124); nicht zu verwechseln mit dem Amt für Sonderprojekte.', 'Sonderabteilung', 'e'),
    g('Amt für Sonderprojekte', 'Geheime Wissenschaftsbehörde (Q-Reihe, Quantentunnel); unter dem Ministerium für Sicherheit und Verteidigung.', 'Amt für Sonderprojekte', 'e'),
    g('Vanhoutte-Fenster', 'Kohärenzfenster, das den makroskopischen Quantentunnel ermöglicht; 2217 von Odile Vanhoutte beschrieben.', 'Vanhoutte-Fenster', 'e'),
    g('Dauerfeld-Störfall', 'Der Wellenantrieb lässt sich nicht abschalten, das Schiff fliegt weiter bis die Energie erschöpft ist.', 'Dauerfeld-Störfall', 'e'),
    g('Raumgeborene', 'Menschen, die auf Schiffen oder Stationen geboren sind; fühlen sich meist dem Gürtel/Ceres oder ihrer Heimatstation zugehörig.', 'Raumgeborene', 'e'),
    g('Tag der Stille', 'Gedenktag an den Koloniekrieg (Jahrestag des Friedens von Occator).', 'Tag der Stille', 'e'),
    g('Dunkelzellen', 'Lichtfreie Kulturen von Schwarzfilm, die Strahlung in Strom wandeln (Ola AG).', 'Dunkelzellen und Schleuder-Räder', 'e'),
    g('Schleuder-Räder', 'Rotierende Habitate mit künstlicher Schwerkraft, von Ostpfad auf Tau Ceti f gebaut.', 'Dunkelzellen und Schleuder-Räder', 'e'),
    g('Raumkonsortien', 'Frühe interplanetare Konzerne (≈ 2060–2095), entstanden aus Fusionen bestehender Firmen.', 'Raumkonsortien und frühe Konzerne', 'e'),
    g('Long-Reach-Ära', 'Zeit der Tiefenraumerkundung und frühen Kolonisation seit 2115, vergleichbar mit der Kolonialzeit, aber ohne Sklaverei und Völkermord.', 'Long-Reach-Ära', 'e'),
    // Einheiten
    g('AE', 'Astronomische Einheit, mittlerer Abstand Erde–Sonne (≈ 149,6 Mio. km).', 'Das Sonnensystem im Jahr 2234'),
    g('ly', 'Lichtjahr, Strecke, die Licht in einem Jahr zurücklegt (≈ 9,46 Bio. km).', 'Sternkarte und Koloniewelten'),
    g('c', 'Lichtgeschwindigkeit (≈ 299.792 km/s); „10c“ bedeutet das Zehnfache.', 'Klassifikation interstellarer & systeminterner Antriebe'),
    g('g', 'Erdbeschleunigung (9,81 m/s²); Maß für Schub und Schwerkraft.', 'Klassifikation interstellarer & systeminterner Antriebe'),
    g('M⊕ / R⊕', 'Erdmasse und Erdradius als Vergleichsgrößen für Planeten.', 'Bewohnte Welten und kolonisierbare Planeten'),
  ],
};
